/**
 * App constants
 */

export default {
	CHANGE_EVENT: 				'CHANGE_EVENT',
	SWITCH_VIEW:				'SWITCH_VIEW',
	GET_CONFIGURATION: 			'GET_CONFIGURATION',
	SAVE_CONFIGURATION:			'SAVE_CONFIGURATION',
	ADD_FIELD: 					'ADD_FIELD',
	REMOVE_FIELD:				'REMOVE_FIELD',
	ADD_INPUT_VALUE:			'ADD_INPUT_VALUE',
	ADD_IGNORED_STYLESHEET:		'ADD_IGNORED_STYLESHEET',
	TOGGLE_ENABLE:				'TOGGLE_ENABLE',
	SET_AUTO_UPDATE:			'SET_AUTO_UPDATE',
	SET_UPDATE_FREQUENCY:		'SET_UPDATE_FREQUENCY',
	SET_KEYBOARD_UPDATE:		'SET_KEYBOARD_UPDATE',
	APPLY_CONFIGURATION:		'APPLY_CONFIGURATION',
	GET_ORIGINAL_STYLESHEETS:	'GET_ORIGINAL_STYLESHEETS'
}
