/**
 * App constants
 */

export default {
	CHANGE_EVENT: 		'CHANGE_EVENT',
	SWITCH_VIEW:		'SWITCH_VIEW',
	GET_CONFIGURATION: 	'GET_CONFIGURATION',
	SAVE_CONFIGURATION:	'SAVE_CONFIGURATION',
	ADD_FIELD: 			'ADD_FIELD',
	REMOVE_FIELD:		'REMOVE_FIELD',
	ADD_INPUT_VALUE:	'ADD_INPUT_VALUE'
}
